#!/usr/bin/env bash
# Per-boot startup: bring up Docker + the local Supabase stack and write the
# app's .env.local so `next dev` can reach the database.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

log() { printf '\n\033[1;36m[start]\033[0m %s\n' "$*"; }

log "Ensuring the Docker daemon is running"
"$REPO_DIR/.cursor/start-docker.sh"

log "Starting the local Supabase stack (idempotent)"
# `supabase start` is a no-op if the stack is already running.
supabase start

log "Writing .env.local from the local Supabase credentials"
API_URL="$(supabase status -o env | sed -n 's/^API_URL="\{0,1\}\([^"]*\)"\{0,1\}$/\1/p')"
ANON_KEY="$(supabase status -o env | sed -n 's/^ANON_KEY="\{0,1\}\([^"]*\)"\{0,1\}$/\1/p')"

if [ -z "$API_URL" ] || [ -z "$ANON_KEY" ]; then
  log "ERROR: could not read Supabase status; is the stack running?"
  supabase status || true
  exit 1
fi

cat > "$REPO_DIR/.env.local" <<EOF
# Auto-generated by .cursor/start.sh for local development. Do not commit.
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
EOF

log "Local Supabase is ready:"
log "  API:    $API_URL"
log "  Studio: $(supabase status -o env | sed -n 's/^STUDIO_URL="\{0,1\}\([^"]*\)"\{0,1\}$/\1/p')"
log "start.sh complete"
